# numpy - numerical python
- probably the single most important python package
- many python packages deal with non trivial amounts of data
    - lists are too time and space inefficient
    - numpy provides
        - contiguous arrays of a single type
        - no 'boxing' of array elements
- more functionality than lists
    - vector arithmetic
    - many convenient methods for modifiying arrays
- advanced array indexing techniques
    - almost identical to Matlab, but:
        - in Python and Numpy 1st index is 0
        - in Matlab and Mathematica 1st index is 1


In [44]:
# numpy is included in the Anaconda distribution

# standard import form for numpy 

import numpy as np

# Sum a numpy array of 1000 guassians - two methods

In [4]:
%%time

import random
meg10 = 10*1000*1000
total = 0

a = np.array([random.gauss(0,1) for j in range(meg10)])

for x in a:
    total += x
    
total

Wall time: 21.4 s


In [5]:
%%time

a = np.random.normal(0, 1, meg10)

[type(a), a.sum()]

Wall time: 672 ms


# Numpy Data Types
- numpy creates many new scalar datatypes
- unlike a list, elements of a numpy array are always all the same type

In [6]:
np.sctypes

{'complex': [numpy.complex64, numpy.complex128],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'others': [bool, object, bytes, str, numpy.void],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]}

# Creating Numpy arrays
- many methods

In [7]:
# convert a list to an array

# note a.nbytes = 24 = 3 * 8
# no per float overhead

a = np.array([1.,2.,3.])
b = np.array([4.,5.,6.])


In [8]:
# lots of meta-information available

a, type(a), a.size, a.shape, a.itemsize, a.dtype, a.nbytes

(array([ 1.,  2.,  3.]), numpy.ndarray, 3, (3,), 8, dtype('float64'), 24)

In [9]:
# note that numpy arrays have a type
# 'a' holds floats

a[0] = 3.4

In [10]:
# an int is converted to float

a[0] = 1234
a[0]

1234.0

In [11]:
# a list is not allowed

a[0] = [4]

ValueError: setting an array element with a sequence.

In [12]:
# 2d nested list => 2d array

[[r+c for c in range(3)] for r in range(3)]

[[0, 1, 2], [1, 2, 3], [2, 3, 4]]

In [13]:
np.array(_)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [14]:
# make arrays w/o starting from lists

np.full((3,3), np.pi)

array([[ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265]])

In [15]:
# common special cases
# just like Matlab

np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
# identity

np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
# like range, endpoint not included

np.arange(2,28,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [19]:
# unlike range, arange works with floats

np.arange(2.4, 8.5, .3)

array([ 2.4,  2.7,  3. ,  3.3,  3.6,  3.9,  4.2,  4.5,  4.8,  5.1,  5.4,
        5.7,  6. ,  6.3,  6.6,  6.9,  7.2,  7.5,  7.8,  8.1,  8.4])

In [20]:
# divide an interval into N-1 equal intervals
# endpoint included

np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [22]:
# standard guassian
# instead of making 9 calls to random.guass, and building a list

np.random.normal(0,1, (3,3))

array([[ 0.52034285,  1.58166155,  0.587672  ],
       [-0.40658136,  0.83560857, -0.5185175 ],
       [ 0.086875  , -0.25247157,  0.10628812]])

# Vector arithmetic
- both more consise and more efficient
- both 'vector op vector', and 'vector op scalar' are defined
- numpy objects define ```__add__, __mul__```, etc

In [23]:
a[0] = 1
[a,b]

[array([ 1.,  2.,  3.]), array([ 4.,  5.,  6.])]

In [24]:
[a + b, a-b, a*b, b/a, a+10, a*10, \
 a.min(), a.max(), a.mean(), a.dot(b)]

[array([ 5.,  7.,  9.]),
 array([-3., -3., -3.]),
 array([  4.,  10.,  18.]),
 array([ 4. ,  2.5,  2. ]),
 array([ 11.,  12.,  13.]),
 array([ 10.,  20.,  30.]),
 1.0,
 3.0,
 2.0,
 32.0]

# time dot product
- in python
- by numpy

In [25]:
d1 = [1.]*1000000
d2 = np.linspace(0,1000, 1000000)
len(d1),len(d2)

(1000000, 1000000)

In [26]:
%%timeit

# python

dot = 0.0
for d in d1:
    dot += d*d


97.9 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
%%timeit

# numpy
d2.dot(d2)

534 µs ± 168 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
# vector functions
# using sin from numpy module, NOT math module
# np.sin acts on each element of a numpy array, 
# and returns a new numpy array
# only one Python float object was created - 2*np.pi

ls=np.linspace(0, 2*np.pi, 5)
print(ls)
print(np.sin(ls))

[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
[  0.00000000e+00   1.00000000e+00   1.22464680e-16  -1.00000000e+00
  -2.44929360e-16]


# Views vs Copies
- numpy arrays have different behavior than lists

In [29]:
x = list(range(15))
y = x[5:10]
# slice is a COPY of x
y[0] = 34545
x,y

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [34545, 6, 7, 8, 9])

In [30]:
x = np.zeros((6,6))
# y is a VIEW into x
y = x[2:5,2:5]
y[0,0] = 1111
x,y

(array([[    0.,     0.,     0.,     0.,     0.,     0.],
        [    0.,     0.,     0.,     0.,     0.,     0.],
        [    0.,     0.,  1111.,     0.,     0.,     0.],
        [    0.,     0.,     0.,     0.,     0.,     0.],
        [    0.,     0.,     0.,     0.,     0.,     0.],
        [    0.,     0.,     0.,     0.,     0.,     0.]]),
 array([[ 1111.,     0.,     0.],
        [    0.,     0.,     0.],
        [    0.,     0.,     0.]]))

In [33]:
# sometimes you do want a copy

x = np.zeros((6,6))
y = x[2:5,2:5].copy()

# x will not see this
y[0,0] = 1111

x,y

(array([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]), array([[ 1111.,     0.,     0.],
        [    0.,     0.,     0.],
        [    0.,     0.,     0.]]))

# boolean arrays
- can be made by 'vector compares'
- can be used as indexes
- super useful

In [67]:
a = sqmat(3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
# make a boolean array
# 'vector op scalar'

b = a > 4
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [69]:
# when a boolean array is used as an index,
# the array elements at the same position 
# as True elements are placed in a 1D array!!


a[b]

array([5, 6, 7, 8])

In [70]:
# 'all' ANDs together all the array elements
# there are False elements, so 'AND' must 
# be False

b.all()

False

In [71]:
# 'any' ORs together all the array elements
# there are True elements, so 'OR' must 
# be True

b.any()

True

In [48]:
o = np.ones((3,3))
r = np.random.randint(0,5,(3,3))
o

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [49]:
r

array([[1, 1, 3],
       [0, 3, 1],
       [3, 3, 0]])

In [50]:
# vector compare - 'vector op vector'
# result of comparison is a boolean array

ba = o == r
ba

array([[ True,  True, False],
       [False, False,  True],
       [False, False, False]], dtype=bool)

In [51]:
# count the Trues

np.count_nonzero(ba), ba.sum(), np.sum(ba)

(3, 3, 3)

In [52]:
# select elements != 1
# 'vector op scalar'
# make a boolean array from a boolean array

ba2 = ba == False
ba2

array([[False, False,  True],
       [ True,  True, False],
       [ True,  True,  True]], dtype=bool)

In [53]:
r[ba2]

array([3, 0, 3, 3, 3, 0])

# Reshaping arrays
- often very useful to change the 'view' or 'interpretation' of an array


In [54]:
a = np.array(range(12))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
b = a.reshape((4,3))
c = a.reshape((2,6))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [57]:
# not the same object

[a is b , a is c]

[False, False]

In [58]:
# but...

a[0] = 55
a

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
b

array([[55,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
# a,b,c are looking at the SAME chunk of data
# so reshape is a cheap operation - it doesn't copy the data

c

array([[55,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [61]:
# the transpose is being done by swapping indexes,
# not by moving data

b.transpose()

array([[55,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [62]:
# raw data is unchanged by transpose

a

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
c

array([[55,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [64]:
b

array([[55,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
# can 'rotate' array

np.rot90(b)

array([[ 2,  5,  8, 11],
       [ 1,  4,  7, 10],
       [55,  3,  6,  9]])

# accessing matrix elements

In [72]:
# make a square matrix

def sqmat(n):
    # make 1D matrix
    a=np.array(range(n*n))
    # reshape to 2D
    s = a.reshape(n,n)
    return(s)

sm = sqmat(4)
sm

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
# Any difference?

[sm[3][2], sm[3,2]] #latter is more efficient because numpy doesnt pull out intermediaries

[14, 14]

In [74]:
# 2d slices

f = sqmat(5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
# pull out a sub matrix

f[2:4, 2:] # not copied

array([[12, 13, 14],
       [17, 18, 19]])

In [78]:
# iterate by row

for r in f:
    print(r)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [79]:
# iterate by element

for e in f.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


# aggregate methods

In [80]:
# sum all the elements

a.sum()

36

In [84]:
# sum columns

a.sum(axis = 0)

array([ 9, 12, 15])

In [82]:
# sum rows

a.sum(axis = 1)

array([ 3, 12, 21])

In [225]:
a.argmax()

11

In [83]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
a.mean()

4.0

In [86]:
a.std()

2.5819888974716112

# Joining arrays

In [87]:
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
np.vstack((f,f))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
np.hstack((f,f))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 20, 21, 22, 23, 24]])

# Spliting arrays

In [90]:
g = sqmat(3)
g

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
# split into column arrays

np.hsplit(g,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [233]:
# split into row arrays

np.vsplit(g, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [234]:
# range only accepts ints

range(5.8, 10.2)

TypeError: 'float' object cannot be interpreted as an integer

In [235]:
# arange takes floats and makes a numpy array

m = np.array(np.arange(5.7,1,-.7))
m

array([5.7, 5. , 4.3, 3.6, 2.9, 2.2, 1.5])

In [236]:
# list index

m[ [1, 3, 2] ]

array([5. , 3.6, 4.3])

# storing/loading arrays to/from files
- lots of ways to do this
- there are also binary formats
- [savetxt doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html)
- [genfromtxt doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html)

In [237]:
import tempfile

path = tempfile.NamedTemporaryFile().name
path


'/var/folders/5_/rfnkj6h171584ptz404k80z00000gn/T/tmptr0_0skg'

In [238]:
a5 = sqmat(5)
a5
a5.dtype

dtype('int64')

In [239]:
# save ints in CSV format

np.savetxt(path, a5, fmt='%i', delimiter=',')

In [240]:
# could read it in like this

with open(path) as f:
    rows = []
    for line in f:
        # get list of strings
        row = line.split(',')
        print(row)
        # convert strings into ints
        rows.append(list(map(int, row)))
    print(rows)
    ra = np.array(rows)

ra

['0', '1', '2', '3', '4\n']
['5', '6', '7', '8', '9\n']
['10', '11', '12', '13', '14\n']
['15', '16', '17', '18', '19\n']
['20', '21', '22', '23', '24\n']
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [241]:
# this is much better

np.genfromtxt(path, delimiter=',', dtype='int64')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Numpy also has a 'matrix' type, in the linear algebra sense
- many functions available
    - inverse
    - equation solving
    - eigenvalues and eigenvectors

In [242]:
a = np.mat("2 4 6;4 2 6;10 -4 18")
a

matrix([[ 2,  4,  6],
        [ 4,  2,  6],
        [10, -4, 18]])

In [243]:
ai = np.linalg.inv(a)
ai

matrix([[-0.41666667,  0.66666667, -0.08333333],
        [ 0.08333333,  0.16666667, -0.08333333],
        [ 0.25      , -0.33333333,  0.08333333]])

In [244]:
im = ai * a
im

matrix([[ 1.00000000e+00, -4.99600361e-16, -1.19348975e-15],
        [-2.77555756e-17,  1.00000000e+00,  8.32667268e-17],
        [ 1.11022302e-16,  1.11022302e-16,  1.00000000e+00]])

In [245]:
im.shape


(3, 3)

In [246]:
# clean up floating point noise

import math

for row in range(im.shape[0]):
    for col in range(im.shape[1]):
        if math.fabs(im[row,col]) < .00001:
            im[row, col] = 0.0
im

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# example - given the vertex positions compute the area of a triangle
- first method - one variable per number

In [92]:
import math

def euclid(x1, y1, x2, y2):
    return math.sqrt( (x1-x2)**2 + (y1-y2)**2 )

In [93]:
euclid(0, 0, 3, 4)

5.0

In [94]:
def area(x1, y1, x2, y2, x3, y3):
    a = euclid(x1, y1, x2, y2)
    b = euclid(x1, y1, x3, y3)
    c = euclid(x2, y2, x3, y3)
    s = (a+b+c)/2
    return math.sqrt(s*(s-a)*(s-b)*(s-c))

area(0, 0, 3, 0, 3, 4)

6.0

- 2nd method - use a two element list to represent a point
- [x,y]

In [95]:
def euclid2(pt1, pt2):
        p1x, p1y = pt1
        p2x, p2y = pt2
        return math.sqrt( (p1x - p2x )**2 + (p2y-p1y)**2 )
    
p1 = [0,0]
p2 = [3,4]
euclid2(p1,p2)

5.0

In [96]:
def area(pts):
    pt1,pt2,pt3 = pts
    a = euclid2(pt1, pt2)
    b = euclid2(pt1, pt3)
    c = euclid2(pt2, pt3)
    s = (a+b+c)/2
    return math.sqrt(s*(s-a)*(s-b)*(s-c))

tri = [[0,0], [3,0], [3,4]]

area(tri)

6.0

- 3rd method - use numpy

In [97]:
import numpy as np

pt1, pt2, pt3  = [np.array(p) for p in [[0,0], [3,0], [3,4]]]

pt2

array([3, 0])

In [98]:
def euclid3(pt1, pt2):
     return np.sqrt(np.power(pt2 - pt1, 2).sum())
    
euclid3(pt1, pt3)

5.0

In [99]:
def area3(pt1, pt2, pt3):
    a = euclid3(pt1, pt2)
    b = euclid3(pt1, pt3)
    c = euclid3(pt2, pt3)
    s = (a+b+c)/2
    return math.sqrt(s*(s-a)*(s-b)*(s-c))

area3(pt1, pt2, pt3)

6.0

# Example - Magic Squares
- a magic square is a 2D square array where all the rows, columns, and both diagonals sum to the same number
- write function 'magic' 
    - if arg is not a 2D square numpy array, raise appropriate errors
    - if arg is not a magic square, return false
    - if arg is a magic square, return the sum
    - don't use any explicit loops
- illustrate various kinds of advanced indexing

In [100]:
def magic(a):
    # check we have a legitimate arg
    if not isinstance(a, np.ndarray):
        raise ValueError('not an array')
    shape = a.shape
    if not 2 == len(shape):
        raise ValueError('not a 2D array')
    if not shape[0]==shape[1]:
        raise ValueError('not square')

    # ok, we have a 2D square numpy array
    side = shape[0]
    
    #  1D array, len = side, of column sums
    colsums = a.sum(axis=0)
    # every sum has to be equal to this one
    sum = colsums[0]
    
    # make 1D, len = side, BOOLEAN array
    # contents of array will be sum == colsum[0], sum == colsum[1]...
    colbools = sum == colsums
    # ok only if each bool is True
    if not colbools.all():
        return False
    
    # check row sums
    rowsums = a.sum(axis=1)
    rowbools = sum == rowsums
    if not rowbools.all():
        return False
    
    # True on major diagonal, other elements False
    boolmajor = np.identity(side, dtype=bool)
    # pull the elements of 'a' corresponding to True
    # in a 1D array
    majordiag = a[boolmajor]
    if sum != majordiag.sum():
        return False

    # check minor diagonal
    boolminor = np.rot90(boolmajor)
    minordiag = a[boolminor]
    if sum != minordiag.sum():
        return False

    # everything worked!
    return [True, sum]
    

In [101]:
# check data type

magic([2,3,4])

ValueError: not an array

In [102]:
# check for 2D

magic(np.array([4,5]))

ValueError: not a 2D array

In [103]:
# not magic

m = np.array([[3, 11,  6],
             [ 9,  7,  5],
             [ 8,  3, 10]])

magic(m)

False

In [104]:
# fix it

m[0,0] = 4
m

array([[ 4, 11,  6],
       [ 9,  7,  5],
       [ 8,  3, 10]])

In [105]:
magic(m)

[True, 21]